#load data
library(foreign)
regress_1<-read.csv("C:\\Users\\s4600479\\Desktop\\REGRESS.csv", sep = ';')
regress_1
attr(regress_1, "variable.labels")
#check data 
names(regress_1)
head(regress_1)
tail(regress_1)
#delimit data
regress_2<-regress_1 [1:465,]
regress_1b<- read.spss("C:\\Users\\s4600479\\Desktop\\REGRESS(2).sav", to.data.frame = TRUE)
#descriptive statistics
mean(regress_2$timedrs)
mean(regress_2$phyheal)
mean(regress_2$menheal)
mean(regress_2$stress)
sd(regress_2$timedrs)
sd(regress_2$phyheal)
sd(regress_2$menheal)
sd(regress_2$stress)
range(regress_2$timedrs, finite = FALSE)
range(regress_2$phyheal, finite = FALSE)
range(regress_2$menheal, finite = FALSE)
range(regress_2$stress, finite = FALSE)

install.packages(e1071)
library(e1071)
#skewness
skewness(regress_2$timedrs)
skewness(regress_2$phyheal)
skewness(regress_2$menheal)
skewness(regress_2$stress)
#kurtosis
kurtosis(regress_2$timedrs)
kurtosis(regress_2$phyheal)
kurtosis(regress_2$menheal)
kurtosis(regress_2$stress)

#package for descrpitive stats
install.packages(psych)
library(psych)
describe(regress_2$timedrs, skew = TRUE, ranges = TRUE)
describe(regress_2$phyheal, skew = TRUE, ranges = TRUE)
describe(regress_2$menheal, skew = TRUE, ranges = TRUE)
describe(regress_2$stress, skew = TRUE, ranges = TRUE)
#plots
install.packages("lattice")
library(lattice)
densityplot(regress_2$timedrs)
densityplot(regress_2$phyheal)
densityplot(regress_2$menheal)
densityplot(regress_2$stress)
boxplot(regress_2$timedrs)
boxplot(regress_2$phyheal)
boxplot(regress_2$menheal)
boxplot(regress_2$stress)
hist(regress_2$timedrs, plot = TRUE)
hist(regress_2$phyheal, plot = TRUE)
hist(regress_2$menheal, plot = TRUE)
hist(regress_2$stress, plot = TRUE)

#new variables transformed
regress_2$log_timedrs<-log(regress_2$timedrs+1)
regress_2$sqrt_timedrs<-sqrt(regress_2$timedrs+1)
regress_2$log_menheal<-log(regress_2$menheal+1)
regress_2$sqrt_menheal<-sqrt(regress_2$menheal+1)
regress_2$log_stress<-log(regress_2$stress+1)
regress_2$sqrt_stress<-sqrt(regress_2$stress+1)
regress_2$log_phyheal<-log(regress_2$phyheal)
regress_2$sqrt_phyheal<-sqrt(regress_2$phyheal)

describe(regress_2$log_timedrs, skew = TRUE, ranges = TRUE)
describe(regress_2$sqrt_timedrs, skew = TRUE, ranges = TRUE)
describe(regress_2$log_menheal, skew = TRUE, ranges = TRUE)
describe(regress_2$sqrt_menheal, skew = TRUE, ranges = TRUE)
describe(regress_2$log_stress, skew = TRUE, ranges = TRUE)
describe(regress_2$sqrt_stress, skew = TRUE, ranges = TRUE)
describe(regress_2$log_phyheal, skew = TRUE, ranges = TRUE)
describe(regress_2$sqrt_phyheal, skew = TRUE, ranges = TRUE)

densityplot(regress_2$log_timedrs)
densityplot(regress_2$log_phyheal)
densityplot(regress_2$log_menheal)
densityplot(regress_2$log_stress)
boxplot(regress_2$log_timedrs)
boxplot(regress_2$log_phyheal)
boxplot(regress_2$log_menheal)
boxplot(regress_2$log_stress)
hist(regress_2$log_timedrs, plot = TRUE)
hist(regress_2$log_phyheal, plot = TRUE)
hist(regress_2$log_menheal, plot = TRUE)
hist(regress_2$log_stress, plot = TRUE)

densityplot(regress_2$sqrt_timedrs)
densityplot(regress_2$sqrt_phyheal)
densityplot(regress_2$sqrt_menheal)
densityplot(regress_2$sqrt_stress)
boxplot(regress_2$sqrt_timedrs)
boxplot(regress_2$sqrt_phyheal)
boxplot(regress_2$sqrt_menheal)
boxplot(regress_2$sqrt_stress)
hist(regress_2$sqrt_timedrs, plot = TRUE)
hist(regress_2$sqrt_phyheal, plot = TRUE)
hist(regress_2$sqrt_menheal, plot = TRUE)
hist(regress_2$sqrt_stress, plot = TRUE)

#to save in .csv
write.csv(regress_2, file = "C:\\Users\\s4600479\\Desktop\\regress_plusTransforms.csv")
